# Generated by Django 5.2.3 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
