# Generated by Django 5.2.3 on 2025-07-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_comment_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='video_url',
            new_name='video_link',
        ),
    ]
