# Generated by Django 5.2.3 on 2025-07-04 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_recipe_prep_time_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
