# Generated by Django 5.2.3 on 2025-07-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_recipe_rating_remove_recipe_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
