# Generated by Django 5.2.3 on 2025-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=5, help_text='Preparation time in minutes'),
            preserve_default=False,
        ),
    ]
