# Generated by Django 5.2.3 on 2025-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
