# Generated by Django 5.2.3 on 2025-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_recipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_autosaved',
            field=models.BooleanField(default=False),
        ),
    ]
