# Generated by Django 5.2.3 on 2025-08-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_recipe_is_autosaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
    ]
